SELECT AVG(Price) FROM Products;

SELECT AVG(Price) AS AVERAGE FROM Products;

SELECT AVG(Price) AS AVERAGE_WHERE FROM Products
WHERE Price > 20 ;

SELECT AVG(Price) AS AVERAGE_GROUPBY FROM Products
GROUP BY CategoryID;
